### ISSUE TITLE
envy shell and custom actions should run from the user's current working directory rather than project root

### ISSUE THREAD

**Issue by magmastonealex** [envy-project/envy#40]
What should the current working directory be for Actions?

My expected behaviour isn't always that they are run from the project root, I expect them to be run from the directory I'm currently in.

**Comment by omstrumpf** [comment]
I agree, I think we should have them execute from the directory you're currently in. Notably thats just for actions, not setup steps, since those definitely expect to be run from the project root.

I'd be in favor of renaming this issue to something like "envy shell and custom actions should run from the user's current working directory rather than project root".
